 ---
- name: "Playbook to Add Key to Newly Provisioned EC2 Instance"
  hosts: hosts_to_add_key
  vars:
    - status : "present"
    - key : "~/Documents/lth.pem"

  tasks:

  - name: "Copy the authorized key file from"
    authorized_key:
      user: "{{ansible_user}}"
      state: "{{status}}"
      key: "{{ lookup('file', '{{ key }}')}}
