apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name  : demo-k8s-cluster
  region: eu-central-1

vpc:
  id: "vpc-75c1041f"  # (optional, must match VPC ID used for each subnet below)
  cidr: "172.31.0.0/16"          # (optional, must match CIDR used by the given VPC)
  subnets:
    public:
      eu-central-1a: {id: "subnet-a676dbcc"}
      eu-central-1b: {id: "subnet-13bfa76e"}
      eu-central-1c: {id: "subnet-44a54b08"}

nodeGroups:
  - name: demo-k8s-node
    instanceType   : t3a.small
    desiredCapacity: 2
    securityGroups:
      withShared: true
      withLocal: false
      attachIDs: ['sg-0344ea586c9fabe4a']
    privateNetworking: false
