apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  labels:
    app: helloworld
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld 
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - image: 197452622020.dkr.ecr.us-east-1.amazonaws.com/helloworld:latest
        imagePullPolicy: Always
        name: helloworld    
        ports:
        - containerPort: 3000
          protocol: TCP
      nodeSelector:
        label: helloworld
---
apiVersion: v1
kind: Service
metadata:
  name: "helloworld-alb"
  namespace: "default"
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: NodePort
  selector:
    app: "helloworld"
